version: 3.5.3+.{build}
clone_depth: 5
branches:
  only:
    - master
    - /\d\.\d/
    - buildbot-custom
build_script:
- cmd: PCbuild\build.bat -e
test_script:
- cmd: PCbuild\rt.bat -q -uall -u-cpu -rwW --timeout=1200 -j0

# Only trigger AppVeyor if actual code or its configuration changes
only_commits:
  files:
    - .github/appveyor.yml
    - .gitattributes
    - Grammar/
    - Include/
    - Lib/
    - Modules/
    - Objects/
    - PC/
    - PCBuild/
    - Parser/
    - Programs/
    - Python/
    - Tools/
